# Copyright (C) 2022 Andrea Ballestrazzi

name: Windows and macOS Build

on:
  push:
    branches-ignore:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/setup-node@v3

    - uses: actions/checkout@v3

    - name: CMake Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: CMake Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
