# Copyright (C) 2015-2021 Johannes Pohl
# Copyright (C) 2022 Andrea Ballestrazzi
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

name: Ubuntu Build and Test

on:
  push:
    branches-ignore:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: CMake Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: CMake Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Unit Tests
      run: cd ./bin && ./popl_test --order rand [unit]

    - name: Functional Tests
      run: cd ./bin && ./popl_test --order rand [functional]
